# Define a reusable step to configure AWS credentials and delete existing versions
name: AWS Beanstalk Deployment
description: Configures AWS credentials, clean up old versions and deploy new version
inputs:
  version:
    description: 'Container version'
    required: true
  docker-username:
    description: 'Docker username'
    required: true
  docker-password:
    description: 'Docker password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.version }}
        push: true
        provenance: false
        platforms: linux/amd64,linux/arm64
        tags: kirschbaumdevelopment/laravel-test-runner:${{ inputs.version }}