name: php-8.3-publish
on:
  push:
    branches:
      - multi-platform
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/docker-publish
      name: Build and Publish (8.3)
      with:
        version: 8.3
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-password: ${{ secrets.DOCKER_TOKEN }}