name: php-8.3-publish
on:
  push:
    branches:
      - multi-platform
jobs:
  publish-amd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: 8.3
        push: true
        provenance: false
        platforms: linux/amd64,linux/arm64
        tags: kirschbaum-development/laravel-test-runner:8.3