name: php-8.3-publish
on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/docker-publish
      name: Build and Publish (8.3)
      with:
        version: 8.3
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-password: ${{ secrets.DOCKER_TOKEN }}
  
  validate:
    runs-on: ubuntu-latest
    needs: publish
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    steps:
    - uses: actions/checkout@v2
    - run: goss --gossfile 8.3/goss.yaml validate